# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-05 01:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=30)),
                ('last_name', models.TextField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_weight', models.IntegerField()),
                ('wight_goal', models.IntegerField()),
                ('photo', models.ImageField(upload_to='')),
                ('goals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PersonalTrainerSite.Customer')),
            ],
        ),
    ]
