# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-06 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalTrainerSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_weight', models.PositiveIntegerField(default=0)),
                ('wight_goal', models.PositiveIntegerField(default=0)),
                ('photo', models.ImageField(upload_to='')),
                ('goals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PersonalTrainerSite.Customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer_goals',
            name='goals',
        ),
        migrations.DeleteModel(
            name='Customer_Goals',
        ),
    ]
